//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OderDetail
    {
        public int id { get; set; }
        public string Avatar { get; set; }
    }
}
